export enum RegistrationStatus {
  SUCCESS = "SUCCESS",
  EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",
  AADHAAR_ALREADY_REGISTERED = "AADHAAR_ALREADY_REGISTERED",
  LAND_REGISTRATION_ALREADY_USED = "LAND_REGISTRATION_ALREADY_USED",
  DATABASE_ERROR = "DATABASE_ERROR",
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
  VERIFICATION_CODE_GENERATION_FAILED = "VERIFICATION_CODE_GENERATION_FAILED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}
